CREATE TABLE usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  tipo VARCHAR(100) DEFAULT 'Cliente',
  tel VARCHAR(20),
  endereço TEXT,
  cpf VARCHAR(30) UNIQUE,
  cep varchar(45),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);



CREATE TABLE produto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao TEXT,
  preco DECIMAL(10, 2) NOT NULL,
  quantidade INT DEFAULT 0,
  codigo VARCHAR(255),
  garantia INT,
  categoria VARCHAR(255),
  marca VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);



CREATE TABLE vendas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  total DECIMAL(10, 2) NOT NULL,  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  endereço TEXT,
  cpf VARCHAR(30),
  cep varchar(45),
  mtd_pay varchar(45),
  sts_venda VARCHAR(45) DEFAULT 'Confirmada',
  FOREIGN KEY (client_id) REFERENCES cliente(id),
  FOREIGN KEY (user_id) REFERENCES usuario(id),
  FOREIGN KEY (product_id) REFERENCES produto(id)
);